Add tests
piero-vic/to-do-list pull request #8
Opened 2021-11-03 23:28 UTC by piero-vic

# Add tests
- Add test for add function
- Add test for remove function

2021-11-03 23:52 UTC, rloterh requested changes
Hi Piero & Jim, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- Test cases are passings
- Test covers **add item** and **delete item** functions
- Tests are grouped using the `description()` method


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-03 23:52 UTC, rloterh commented on test/app.test.js
> +describe('Tests for todo list app', () => {
- [ ] Other _pure functions_ in your code are **not tested** aside _add item_ and _delete item_. Kindly ensure to test **all** pure functions such as the _edit_, _complete: true/false_, _clear_ all completed_ and other created pure functions.

2021-11-03 23:52 UTC, rloterh commented on test/mock/todoList.js
> +export default class ToDo {
- [ ] Local storage is not included in your test mock functions. Kindly ensure that `local storage, `DOM` or external APIs uses test functions defined as a mock.

2021-11-04 00:04 UTC, piero-vic commented on test/app.test.js
> +describe('Tests for todo list app', () => {
Hi. According to the instuctions [here](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_1.md). We should only implement tests for the add and remove functionality. the other tests are going to be implemented on the [next activity](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_2.md)

2021-11-04 00:09 UTC, piero-vic commented on test/mock/todoList.js
> +export default class ToDo {
We are using an npm package to handele the local storage mock. It's declared here.
https://github.com/piero-vic/to-do-list/blob/6cb2a47801100ceb6689b90a6015918785db986b/package.json#L38
And the configuration is here.
https://github.com/piero-vic/to-do-list/blob/6cb2a47801100ceb6689b90a6015918785db986b/package.json#L10-L11
Thanks for the feedback.

2021-11-04 06:36 UTC, rloterh commented on test/app.test.js
> +describe('Tests for todo list app', () => {
Hi @piero-vic 
Here is a screenshot of this project requirement (Kindly look at it carefully):
![image](https://user-images.githubusercontent.com/12745474/140268699-3fe3cd8a-3957-4a66-9376-0afc763b4502.png)

2021-11-04 06:37 UTC, rloterh commented on test/mock/todoList.js
> +export default class ToDo {
Hi @piero-vic 
You are very right on this aspect. I will leave a note for the same!

2021-11-04 07:24 UTC, rloterh commented
**Hi Fellow Code Reviewer:**

Kindly note, mock function for local storage was implemented using dependencies, as indicated above. I apologize for missing this important step.

2021-11-04 11:42 UTC, piero-vic commented on test/app.test.js
> +describe('Tests for todo list app', () => {
Hi. Thank you for the response. I appreciate it. I'm having concerns about what are we going to do in the next activity if we implement all the tests in this pull request. This are the requirements for the [next activity](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_2.md).
![project-requirements](https://user-images.githubusercontent.com/71156605/140306409-208797a2-a288-4c99-9965-57e0f9a3e8f0.png)
Thanks you again. I look forward to your reply.

2021-11-04 14:39 UTC, piero-vic commented
Hi. Please take into consideration that we are implementing tests just for the add and remove funcitonality. Since the other funtionality it's goint to be tested in the [next activity](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_2.md).
![project-requirements-1](https://user-images.githubusercontent.com/71156605/140333779-1ae6db42-9659-4453-a17e-fbca0415966e.png)

2021-11-04 14:49 UTC, dasileker approved these changes
## **Hi @piero-vic,** 

### **Optional**

- As The TSE said the pure function can be added, and also you are correct but you can add more test suits even if you add those.

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 14:55 UTC, merged